#!/bin/bash

if [ -r ~/.xinit-session-rc ]
then
    . ~/.xinit-session-rc
fi

new_csum=$(sha1sum ~/.local/bin/dwm)
csum=""
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm 2> ~/.dwm.error.$RANDOM.log
    else
        exit 0
    fi
    new_csum=$(sha1sum ~/.local/bin/dwm)
    sleep 0.5
done

