#!/bin/sh
#命令别名
if [ -n "${NVIM_LISTEN_ADDRESS+x}" ]; then
    alias vim="~/.config/nvim/send_command_to_vim.py"
    alias vi="~/.config/nvim/send_command_to_vim.py"
else
    alias vim='nvim'
    alias vi='nvim'
fi
alias grep="grep --color=auto"
alias cls='tput reset'
alias chrome="google-chrome"
alias top='htop'
alias codeit='code . && exit'
alias apt_proxy='apt -o Acquire::http::proxy="http://127.0.0.1:8118/"'
# fuzzy的cd跳转
alias cdto='cd $(find -type d | fzf)'
alias q="exit"
# 构建指令
alias cmake='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON '
# my mpc
alias mpc='mpc --host=localhost --port=16600'

upgrade_finish(){
    echo "更新完成" | espeak -v zh
}
# 命令行使用剪贴板
case "$(uname -s)" in
    Linux*) 
        alias tocopy='xclip -selection c'
        alias fromcopy='xclip -selection clipboard -o'
        ;;
    Darwin*)
        alias tocopy='pbcopy'
        alias fromcopy='pbpaste'
        ;;
esac


export TASKDDATA=~/.tasked
mkdir -p $TASKDDATA

#ros相关
#export ROS_HOSTNAME=192.168.188.233
#export ROS_MASTER_URI=http://192.168.188.2:11311

PATH=~/.cargo/bin:~/.nix-profile/bin:~/.local/bin:~/bin:/opt/ghc/bin:~/.cabal/bin:~/.stack/programs/x86_64-linux/ghc-8.2.2/bin:$PATH
PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs

# 消除ctrl+s锁定
# 参考https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon

# CUDA
# export PATH=/usr/local/cuda/bin:$PATH
# export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# rust proxy
export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup

# vim mode
set -o vi

# man colorful
export LESS_TERMCAP_mb=$'\E[1m\E[32m'
export LESS_TERMCAP_mh=$'\E[2m'
export LESS_TERMCAP_mr=$'\E[7m'
export LESS_TERMCAP_md=$'\E[1m\E[36m'
export LESS_TERMCAP_ZW=""
export LESS_TERMCAP_us=$'\E[4m\E[1m\E[37m'
export LESS_TERMCAP_me=$'\E(B\E[m'
export LESS_TERMCAP_ue=$'\E[24m\E(B\E[m'
export LESS_TERMCAP_ZO=""
export LESS_TERMCAP_ZN=""
export LESS_TERMCAP_se=$'\E[27m\E(B\E[m'
export LESS_TERMCAP_ZV=""
export LESS_TERMCAP_so=$'\E[1m\E[33m\E[44m'

case "$(uname -s)" in
    Linux*) ;;
    Darwin*)
        export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"
        export PATH="/usr/local/opt/gettext/bin:$PATH"
        export PATH="$PATH:/usr/local/bin"
        export PATH="$PATH:/Library/Apple/usr/bin"
        export ANDROID_HOME="$HOME/Library/Android/sdk" 
        export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
        export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home
        export PATH="$PATH:$ANDROID_HOME/platform-tools"
        export PATH="$HOME/Downloads/code.app/Contents/Resources/app/bin:$PATH"
        export GOPATH="$HOME/go"
        export CXXFLAGS=-isystem\ /usr/local/Cellar/llvm/9.0.0/include/c++/v1
        ;;
esac
