#!/bin/sh
# openrave
_openrave_load(){
    #OPENRAVE_PATH=$(openrave-config --python-dir)
    OPENRAVE_PATH=/opt/ros/kinetic/lib/python2.7/dist-packages
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OPENRAVE_PATH/openravepy/_openravepy_
    export PYTHONPATH=$PYTHONPATH:$OPENRAVE_PATH
}

# _openrave_load

#命令别名
alias vi='vim'
alias grep="grep --color=auto"
alias cls='reset'
alias chrome="google-chrome"
alias top='htop'
alias codeit='code . && exit'
# fuzzy的cd跳转
alias cdto='cd $(find -type d | fzf)'
# 命令行使用剪贴板
tocopy() {
    xclip -selection c 
}

export TASKDDATA=~/.tasked
mkdir -p $TASKDDATA

#ros相关
#export ROS_HOSTNAME=192.168.188.233
#export ROS_MASTER_URI=http://192.168.188.2:11311

PATH=~/bin:/opt/ghc/bin:~/.cabal/bin:$PATH

# 消除ctrl+s锁定
# 参考https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon

# CUDA
# export PATH=/usr/local/cuda/bin:$PATH
# export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# vim mode
set -o vi

# man colorful
export LESS_TERMCAP_mb=$'\E[1m\E[32m'
export LESS_TERMCAP_mh=$'\E[2m'
export LESS_TERMCAP_mr=$'\E[7m'
export LESS_TERMCAP_md=$'\E[1m\E[36m'
export LESS_TERMCAP_ZW=""
export LESS_TERMCAP_us=$'\E[4m\E[1m\E[37m'
export LESS_TERMCAP_me=$'\E(B\E[m'
export LESS_TERMCAP_ue=$'\E[24m\E(B\E[m'
export LESS_TERMCAP_ZO=""
export LESS_TERMCAP_ZN=""
export LESS_TERMCAP_se=$'\E[27m\E(B\E[m'
export LESS_TERMCAP_ZV=""
export LESS_TERMCAP_so=$'\E[1m\E[33m\E[44m'
