#!/bin/sh
# 在窗口管理器启动之前运行的脚本
# 解决xcompmgr背景变灰色的帮助来自https://wiki.archlinux.org/index.php/Xcompmgr_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

if [ -f ~/.picture/background.jpg ];then
feh --bg-fill ~/.picture/background.jpg
else
hsetroot -solid "#fff"
fi
# 挂载所有硬盘

loadDisk(){
    a=$(lsblk -f --output label)
    for x in $a
        do
        if [ $x != 'KNAME' ] ;then
            lsblk -f --output label,size | grep $x | grep [0-9]*.[0-9]*G && test=$(lsblk -f --output kname,label | grep $x | awk '{print $1}') && udisksctl mount -b /dev/$test
        fi
    done
}

# loadDisk &

fan &

# 预先加载shutter
shutter --min_at_startup &

# 允许窗口透明
compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc --unredir-if-possible

# 执行键盘按键重映射
xmodmap ~/.xmodmap

# indicator-cpufreq
indicator-cpufreq&

# 坚果云同步
python2 ~/.nutstore/dist/bin/nutstore-pydaemon.py&

# 开启小键盘
numlockx on

# 屏幕常亮
setterm -blank 0 -powerdown 0

autocutsel &

# 禁用redshift的自启动程序
systemctl --user stop redshift.service&

mpd&

~/.touchpad.sh &

# 剪贴版管理器
# copyq&
